AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectId:
    Description: AWS CodeStar projectID used to associate new resources to team members
    Type: String
Resources:
  MljsPlaceholderBucket:
    Properties:
      AccessControl: PublicRead
    Type: AWS::S3::Bucket
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar
